CREATE TABLE STUDENT (ID INT, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255),
CREATE_DATE DATE, UPDATE_DATE DATE, STATUS VARCHAR(255));

INSERT INTO STUDENT VALUES ( 6261, 'GAURAV', 'PURI', SYSDATE, SYSDATE, 'ACTIVE');
INSERT INTO STUDENT VALUES ( 6262, 'KIRAN', '', SYSDATE, SYSDATE, 'ACTIVE');
